### ISSUE TITLE
Images for wiki

### ISSUE THREAD

**Issue by Hamdy** [Jumpscale/jumpscale_core7#1]
![9_03](https://cloud.githubusercontent.com/assets/526328/5579704/a8f9aec8-9047-11e4-9a45-e2c756f15d4f.jpg)

**Comment by Hamdy** [comment]
![login](https://cloud.githubusercontent.com/assets/526328/8205659/2469402c-14fb-11e5-81f5-69e87405e294.png)

**Comment by despiegk** [comment]
this structure is no longer valid, we are going to new architecture
