### ISSUE TITLE
Ignore nodes that are not active in healtcheck

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#125]
Healtcheck currently reports nodes that have active flag false as halted (if they are idd not running). We need to ignore the not active nodes.
Make sure this status of this flag is visible in the node details page.

CBGrid has an option to put a stack in disabled state make sure we update the node aswell during this action

see: http://cpu01.bracknell1.vscalers.com:8282/grid/checkstatus

**Comment by rkhamis** [comment]
is this still relevant?

**Comment by despiegk** [comment]
is this still the case,
lets check

**Comment by Hamdy** [comment]
Already taken care of
