### ISSUE TITLE
kvm extension improvements

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#127]
* code is not defensive enough for when creation fails, the machine needs to be deleted no matter what when starting new
* do masquerading on pub interface, so std the pub interface can get to outside world ! 
* implement execute function to kvm extention (which will use ssh to execute a cmd inside the vm)
* create jskvm
* implement snapshots & mounting
* implement windows (sameh will create image)

the tasks above are sorted following priority

**Comment by rkhamis** [comment]
is this done or just closed, if done where is doc?

**Comment by despiegk** [comment]
we also need a way to connect to a specific openvswitch bridge
so we can use this to instrument a machine in a OVC environment

**Comment by rkhamis** [comment]
Done
