### ISSUE TITLE
sync in agentcontroller 2 should be as subprocess & optional

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#132]
agent2 & agentcontroller2 should run the syncthing as a subprocess
there should be instrumentation in agent to query about this process & see logs
like for any cmd

create documentation how to use this embedded sync tool
how to sync other directories

there should be method to turn the sync daemon on & off on agentcontroller as well as on any agent

the client should easily support this

**Comment by muhamadazmy** [comment]
This already implemented for agent2

**Comment by muhamadazmy** [comment]
But - on the other hand - agentcontroller2 will still depend on syncthing package and will get installed as a dependency for 2 reasons:

1- AC2 doesn't built to run sub-processes,  and we shouldn't overload it with such complexity.
2- AC2 will always be part of a working jumpscale installation (including ays)
