### ISSUE TITLE
agentcontroller 2 docu

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#134]
# tutorial custom cmds
see tutorial:
Adding custom execute cmd to Agent

not clear, paths are not described well and are not correct I thing

# high level & low level info
- we should create a section where we explain how it works on low level
- see original specs
- the different outputs on std out
- how to return result
- so the internals basically

- then we need info for the high level usage
- a std users should NOT have to know about this
- client methods should reflect the high level constructs
- the low level is for a developer who creates a client
- this needs to be clear

**Comment by muhamadazmy** [comment]
This describes the simple internals of the client.

https://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Internals.html
