### ISSUE TITLE
AYS reinstall

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#23]
Reinstall in AYS is broken

**Comment by zaibon** [comment]
Reinstall rely on [resetstate](https://github.com/Jumpscale/jumpscale_core7/blob/master/lib/JumpScale/baselib/atyourservice/Service.py#L706) and [reset](https://github.com/Jumpscale/jumpscale_core7/blob/master/lib/JumpScale/baselib/atyourservice/Service.py#L719) actions which as not yet been ported for AYS

**Comment by zaibon** [comment]
can you review and close if fixed ?

**Comment by despiegk** [comment]
fixed
