### ISSUE TITLE
AYS flow stops on dependency error

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#24]
If a service has a dependency on another package that doesn't start for some reason, it doesn't go on with its flow. This is both confusing (because no errors are shown) and incorrect, because the installation (or at least the copying of the files) itself should not rely on another service starting/completing first.

**Comment by zaibon** [comment]
Can you give me hints how te reproduce ?

**Comment by rkhamis** [comment]
Create a service that doesn't work for any reason. For instance, its start is buggy.
Put it as a dependency to your test package and you'll find the recipe itself doesn't get executed.
