### ISSUE TITLE
AYS domains

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#25]
All the hrds are prepended with jumpscale__. Should it not be [domain]__?

**Comment by zaibon** [comment]
yes it should be [domain]_
Domain names are loaded from /opt/jumpscale/hrd/system/atyourservice.hrd 
(have a look [here](https://github.com/Jumpscale/jumpscale_core7/blob/master/lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py#L48) )
Do you have any other domain than jumscpale in atyourservice.hrd ?

**Comment by despiegk** [comment]
is working
