### ISSUE TITLE
documentation can be converted to html5 website using hugo

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#28]
hugo is a nice tool to convert markdown to a static website.
we will host this static website to give the user a nicer experience to see our documentation
the documentation needs to stay 100% compatible with github wiki system

**Comment by despiegk** [comment]
publish on main jumpscale website & bring it all together
or am I naive and it won't work that way?

**Comment by karimal** [comment]
Since Hugo markdown isn't completely standard markdown, it also has extra features - like hugo parameters - which we are using in Jumpscale website, 

so I 'll try this first because I'm not so sure that Github supports Hugo.
Thanks

**Comment by despiegk** [comment]
can we self host it into our own portal?
maybe we can find a way to convert what is in wiki github to what we need for hugo with some smartly chosen bits of info?
can we do same for our own portal,would be nice if our portal can self host documentation
