### ISSUE TITLE
golang based agent

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#31]
functions
* process management (all processes deployed by ays are managed by this process manager)
* capture stats about these managed processes & send to agentcontroller
* run lua & python jumpscripts (as sub processes)
    * stdout/err is mapped to events, logs, results, ...
* port redirection between agents e.g. expose ssh port on this node on 2222 on another agent all over websockets server which is running next to agent controller
* statsd aggregator function in agent (there is golang aggregator already, need to adjust so it can report to agentcontroller)

changes with python version
* no more need for redis
* logs are not send centrally they are stored on agent

**Comment by grimpy** [comment]
Issues are tracked @ https://github.com/Jumpscale/jsagent
