### ISSUE TITLE
ays in jsportal

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#34]
# jsportal integration

## api

- need rest api for querying about ays services & templates
- also for executing actions

## @ys cache

- walk over all ays service objects & templates populate through SQLAlchemy a sql database
	- do this by using our j.ays... classes 
- use an hrd to specify which @ys repo's to use & which sql db as cache (see below)
- this is for readonly ! all changes are done on the text files of the @ys tree
- put python eve on top (uses the same sqlalchemy classes) so our macro's work in portal with search ...

```
ays.1 = 
    name:'my_@ys',
    git:'https://kds:1234@git.aydo.com/racktivity/ays.git',
    sqlconnection:'postgresql://scott:tiger@localhost:5432/my@ys',
    gitupdate:30 #means every 30 seconds update from git
    
ays.2 = 
    name:'anotherone',
    git:'https://kds:1234@git.aydo.com/anotherone/ays.git',
    sqlconnection:'postgresql://scott:tiger@localhost:5432/anotherone',
    gitupdate:30 #means every 30 seconds update
    
```

## update git recurring job

- have a job in portal (which uses local agent for async jobs) for updating the git's for @ys

### ays\_service\_list 

- arguments
	- domain (optional)
	- name (optional)
	- instance (optional)
	- category (optional)
	- parent (optional) is 1 of parents and specified as name:instance
	- child (optional) is 1 of children and specified as name:instance
- list all services in grid with search
- show domain,name,instance, category and a link to the service page

### ays\_service\_template\_list
- arguments
	- domain (optional)
	- name (optional)
	- category (optional)
- list all servicetemplates in grid with search
- show domain,name, category and a link to the servicetemplate page

### ays\_service

is maybe not a page but using the embedded template functionality !
which would be better !!!

- arguments
	- domain
	- name
	- instance
- can specify only e.g. name but then need to be sure there is only 1
- visualize everything relevant about ays service
	- also description (is markdown format)
	- in code block the hrd
	- in code block the actions file
	- link to children
	- link to parents

### ays\_service\_actions

- arguments
	- domain
	- name
	- instance
- can specify only e.g. name but then need to be sure there is only 1
	- show the actions which can be executed on service

### ays\_service\_template

is maybe not a page but using the embedded template functionality !
which would be better !!!

- arguments
	- domain
	- name
- can specify only e.g. name but then need to be sure there is only 1
- visualize everything relevant about ays service template
	- also description (is markdown format)
	- in code block the hrd
	- in code block the actions file
	- show grid with services which are coming from this template
 
- possible actions:
	* 	prepare
	* 	install
	* 	configure
	* 	start
	* 	stop
	* 	halt (kill)
	* 	check_up_local
	* 	check_down_local
	* 	check_requirements (for install)
	* 	montor_local (is like a health check)
	* 	montor_remote (is like a health check)
	* 	cleanup
	* 	data_export arg
	* 	data_import arg
	* 	removedata
	* 	uninstall
	* 	test

### ays\_service\_template\_actions

- arguments
	- domain
	- name
- can specify only e.g. name but then need to be sure there is only 1
	- show the actions which can be executed on service template
- possible actions:
	* 	new
	*  build 
	*  package

**Comment by despiegk** [comment]
what is status
where are docs? (please put in docs for jumpscale7)
does this work with sqllite

please create an ays which does full deployment of a test environment on ms1
complete:
https://github.com/Jumpscale/play7/tree/master/ays_portal

**Comment by rkhamis** [comment]
AYS portal is now part of the gridportal installation

Works with SQLAlchemy and all done
