### ISSUE TITLE
update doc for osis/ros

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#37]
all osis docs under
/Users/despiegk/Documents/code/github/jumpscale/jumpscale_core7.wiki/Devel/Docs/OSIS
please check all doc, especially around osis eve

**Comment by Hamdy** [comment]
ROS documentation is already uptodate
Please check : https://github.com/Jumpscale/jumpscale_core7/wiki/ROs
and https://github.com/Jumpscale/jumpscale_core7/wiki/ModelSpec
