### ISSUE TITLE
api doc does not work in system page

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#45]
![selection_048](https://cloud.githubusercontent.com/assets/6021844/9062176/012d39e2-3ac1-11e5-98c0-2b72dc2257c5.png)

**Comment by grimpy** [comment]
Requires more details this means one of the actors if failing to load.

**Comment by grimpy** [comment]
https://github.com/Jumpscale/jumpscale_portal/commit/4b84cd4581236c5be9b5eb9d2c730db4401c42a2

This commit will give user better message about what is going on

**Comment by grimpy** [comment]
![150804_164836](https://cloud.githubusercontent.com/assets/143869/9063973/824e7b36-3aca-11e5-9b78-020f56bdb2a4.png)
Example of new output
