### ISSUE TITLE
created a new space (which is really cool) but then the layout was very weird

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#46]
think we need to do some cleanup, would be nice this works because then our customers can use this to put custom macro's in
but the default space content should be clean & easy & neutral

![selection_051](https://cloud.githubusercontent.com/assets/6021844/9062374/54ab61ce-3ac2-11e5-871f-d5d40f946643.png)

**Comment by despiegk** [comment]
can we stay close to the std look and feel like in system

**Comment by despiegk** [comment]
let's take a different approach
reem knows how

**Comment by despiegk** [comment]
lets for now just create a space which uses the markdown format

**Comment by despiegk** [comment]
christophe has changed the way how we load markdown
should be exactly same codepath as .wiki
now we convert .md first to .mike and then same codepath
please check create space works in right way and this new codepath works

**Comment by karimal** [comment]
yes we already tested it with full cycle of create new space in markdown mode, and it's working fine UI wise and exactly the same with .wiki portal looking.
