### ISSUE TITLE
ros home page should show something

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#48]
e.g. overview of services
links to subsections

![selection_053](https://cloud.githubusercontent.com/assets/6021844/9078442/b22b6e44-3b3e-11e5-818c-3bebcabb570d.png)

**Comment by Hamdy** [comment]
![swagger ui](https://cloud.githubusercontent.com/assets/526328/9088059/d46c7f7c-3b96-11e5-9b2f-f9c82befdd7c.png)
