### ISSUE TITLE
please check/fix osis2 I can't get it to work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#57]
![selection_072](https://cloud.githubusercontent.com/assets/6021844/9292170/dd563f5a-43e9-11e5-8020-82335f5b2f96.png)
could be because of my refactoring of names

**Comment by despiegk** [comment]
please make sure you remove your apps/ros & also all hrd's to do with it & stop before testing new

**Comment by despiegk** [comment]
check doc on
http://despiegk.gitbooks.io/jumpscale/content/OSIS/OSIS2/OSIS2.html
change where required (see jumpscale/docs repo)

**Comment by Hamdy** [comment]
I don't really agree with you on changing name to OSIS2
*  Excusable shouldn't hold version number.
*  Renaming files results in much changes else where (i.e in packages), possibly break other tested areas
* I see renaming process here in master branch is also redundant as eventually old OSIS will not be used any way and will be replaced totally with ROS/OSIS2.
    *  We already have a separate branch for this that partially works (with no old osis)
    *  What after ROS fully replaces OSIS will we make its name osis? 

What do u think?

**Comment by despiegk** [comment]
sorry, we have no choice, I simply don't want to confuse people right now
and others have done the same
apache2
python2 & python3

so please go ahead and make sure all works using agent2 agentcontroller2




On Sun, Aug 16, 2015 at 1:21 PM, Hamdy <notifications@github.com> wrote:

> I don't really agree with you on changing name to OSIS2
>
>    - Excusable shouldn't hold version number.
>    - Renaming files results in much changes else where (i.e in packages),
>    possibly break other tested areas
>    - I see renaming process here in master branch is also redundant as
>    eventually old OSIS will not be used any way and will be replaced totally
>    with ROS/OSIS2.
>       - We already have a separate branch for this that partially works
>       (with no old osis)
>       - What after ROS fully replaces OSIS will we make its name osis?
>
> What do u think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core7/issues/57#issuecomment-131528472>
> .
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by grimpy** [comment]
docs are now @ http://gig.gitbooks.io/jumpscale/content/

**Comment by Hamdy** [comment]
Fixed by this commit https://github.com/Jumpscale/jumpscale_core7/commit/f69bd6d0a53c86a58e7e3d05795e5d3ee293a5e4
![screenshot from 2015-08-09 10 23 35](https://cloud.githubusercontent.com/assets/526328/9331211/cc14cdc2-45c6-11e5-8472-a6e715d8e6a0.png)

Docs seems fine too.
Unit tests ran smoothly as well.
Will continue in running the whole thing with agentcontroller2, agent2
