### ISSUE TITLE
make sure agentcontroller2 is used like that everywhere

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#58]
change name of binary to agentcontroller2
same for other code & config files
be consistent
update docs (in jumpscale/docs repo)

**Comment by despiegk** [comment]
also in build system changes will be required
i've already changed the ays names

**Comment by muhamadazmy** [comment]
Should we also change the agent name from superagent to agent2 ? or leave it as it is

**Comment by despiegk** [comment]
agent2

I've done most if it, I hope

On Sun, Aug 16, 2015 at 8:34 AM, Muhamad Azmy <notifications@github.com>
wrote:

> Should we also change the agent name from superagent to agent2 ? or leave
> it as it is
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core7/issues/58#issuecomment-131495128>
> .
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
Well, I just had to change the `build` process to use the new repo names (also in code changed the go imports to use the correct paths), also updated the tests and ms1drive script to use the correct packages names.

I will move on to documentation now

**Comment by muhamadazmy** [comment]
Docs is now up-to-date https://github.com/Jumpscale/agent2/wiki
