### ISSUE TITLE
vnas instrumentation

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#61]
create ays package to test a full instrumentation for vnas

- use ms1client ays
- deploy in space in OVC  
    - master (ays vnas_master) (*)
        - is git/ays repo (from which all further installs happen, even own install)
        - influxdb 
        - portal
        - agentcontroller2
        - redis
        - osis
        - grafana
    - vnas active directory (ays vnas_ad)
        - active directory (samba 4)
        - create some test users (use ays vnas_ad_user which consumes service from vnas_ad)
    - vnas backend 1-5 (ays vnas_stor)
        - nfs server
        - exposes X virtual disks (X is param), each disk exposed individual as nfs mount
            - use (ays vnas_stor_disk) with as parent the vnas_stor, each has unique id (int)
            - put vnas.toml on root of vnas_stor_disk (can find the id there & other relevant info)
    - vnas 1-5 (ays vnas_node)
        - samba 4 as client to active director installed above
        - mount all vnas_stor_disks from all vnas_stor's (use ays to find)
            - mount as /Storage/vnas/$id
    - vnas_lb (ays vnas_lb)
        - loadbalancer on TCP level (use routeros?) balances users over the vnas'es
    - on each node there is agent2 installed
        - script is created to do monitoring & use stats capabilities

remarks
- (*) bootstrap
   - first vmachine has git repo
   - git repo on git.aydo...
   - this git repo is ays basis to install everything described above
- influxdb
    - don't use statsd ! aggregate in agent & send on agentcontroller to influxdb
    - use the tags on influxdb
    - create space which allows users to see grafana and play with the stats

**Comment by zaibon** [comment]
I can take this one, I already have most the the scripts done, just need to adapt into an AYS.

Where sits the loadbalance of the disks ? Should be on the vnas where the disk are mounted right ?

**Comment by despiegk** [comment]
need to move this story to other location & finetune

On Sat, Sep 5, 2015 at 1:59 PM, Christophe de Carvalho <
notifications@github.com> wrote:

> I can take this one, I already have most the the scripts done, just need
> to adapt into an AYS.
>
> Where sits the loadbalance of the disks ? Should be on the vnas where the
> disk are mounted right ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core7/issues/61#issuecomment-137947955>
> .
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by despiegk** [comment]
task moved to
https://youtrack.incubaid.com/issue/devgig-479?query=project%3A+prod-mountaintop
