### ISSUE TITLE
gitbook does not publish?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#64]
if we can't fix, deploy gitbook on a mothership1 operations space
& fix url's
and do automatic checkout of doc every 5 min

**Comment by grimpy** [comment]
I contacted gitbook support will keep this ticket updated.

My Mail

```
https://www.gitbook.com/book/gig/jumpscale/edit#/edit/master/Howto/How%20To%20Use%20Docker.md

When making changes adding or editing pages my online book @ https://www.gitbook.com/book/gig/jumpscale/details doesnt reflect the updates?
The backend repo for the book is @ https://github.com/Jumpscale/docs
Which has a hook configured for gitbook.


Greetings, Jo
```

Reply

```
Your request (1156) has been received and is being reviewed by our support staff.

To add additional comments, reply to this email.
````

**Comment by grimpy** [comment]
Reply

```
Hi Jo,

It looks like your book is building (it has been updated a few hours ago), you can follow builds at https://www.gitbook.com/book/gig/jumpscale/activity

Best Regards,
Samy
````
Conclusion it takes time to build in the history tab we can see if something is building or even force it to build.

**Comment by despiegk** [comment]
not true
i've tried to force building, didn't work

On Mon, Sep 7, 2015 at 1:26 PM, Jo De Boeck <notifications@github.com>
wrote:

> Reply
>
> Hi Jo,
>
> It looks like your book is building (it has been updated a few hours ago), you can follow builds at https://www.gitbook.com/book/gig/jumpscale/activity
>
> Best Regards,
> Samy
>
> Conclusion it takes time to build in the history tab we can see if
> something is building or even force it to build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core7/issues/64#issuecomment-138274551>
> .
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk
