### ISSUE TITLE
purge of jobs/eco's does not seem to work

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#71]
i've added in jsgrid possibility to remove jobs.ecos
doesn't seem to work, need this urgently

**Comment by rkhamis** [comment]
![screenshot - 04152014 - 08 3a40 3a03 am](https://cloud.githubusercontent.com/assets/8425762/9793160/5880601c-57e4-11e5-9507-57f24579951a.png)

**Comment by grimpy** [comment]
Fixed in jsgrid
