### ISSUE TITLE
check redis is running is not cost effective

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#74]
5 jumpscale:processmanager 14:58:46: exec:netstat -ntulp | grep ':7768 '
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:netstat -ntulp | grep ':7766 '
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:netstat -ntulp | grep ':7767 '
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:netstat -ntulp | grep ':7769 '
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef
5 jumpscale:processmanager 14:58:46: exec:env COLUMNS=300 ps -ef

**Comment by rkhamis** [comment]
we need rewrite so there is only 1 ps ... happening

**Comment by despiegk** [comment]
will be done differently with new agent
