### ISSUE TITLE
When jumpscale application has a pid registered of other process it falsely claims its running

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#90]
Check what we can do with old pids

**Comment by despiegk** [comment]
will be done differently with new agent, close for now

On Thu, Sep 10, 2015 at 4:55 PM, Reem Khamis <notifications@github.com>
wrote:

> Check what we can do with old pids
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jumpscale_core7/issues/90>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk
