### ISSUE TITLE
over view page needs much better

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#95]
make new graphs (these are fake)
- show nr of vmachines
- show nr of cpu nodes
- show nr of accounts/spaces
- status of health but now not layout nice

**Comment by rkhamis** [comment]
Nr of vmachines in gauage and nr of events are not fake

**Comment by despiegk** [comment]
just check that only non fake are there

**Comment by grimpy** [comment]
Has been cleaned up since ticket was created
